{
 "title": "Mistle Application Monitoring",
 "tags": [
  "devops",
  "mistle"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System CPU Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "Docker Containers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "count(container_last_seen)" }
   ]
  },
  {
   "title": "HTTP Response Times",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nginx_http_request_duration_seconds"
    }
   ]
  }
 ]
}