global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:80']
    metrics_path: /metrics

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']

  # Custom application metrics (if available)
  - job_name: 'mistle-app'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: /metrics
    scrape_interval: 30s
